# Generated by Django 5.1.7 on 2025-03-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySkill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='duration',
            field=models.FloatField(),
        ),
    ]
