# Generated by Django 5.1.7 on 2025-03-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySkill', '0002_courses_slug_alter_courses_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='courses',
        ),
    ]
