# Generated by Django 5.1.7 on 2025-03-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySkill', '0003_event_delete_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
